# https://giscus.app
# https://github.com/badboy/mdbook-mermaid

[book]
title = "Kusion Cookbook 中文版"
authors = ["Kusion云原生爱好者"]
description = "通过配置编程化方式实践云原生IaC"
language = "zh"
multilingual = false
src = "."

[build]
build-dir = "book"

[output.html]
additional-css = ["style.css"]
additional-js = ["js/custom.js", "js/bigPicture.js"]
git-repository-url = "https://github.com/awesome-kusion/kusion-cookbook"
edit-url-template = "https://github.com/awesome-kusion/kusion-cookbook/edit/master/{path}"
git-repository-icon = "fa-github"
